import React from 'react'
import ConnectDiagram from './assert/proj_5/Connection_diagram.png'
import img1 from './assert/proj_5/1.png'
import img2 from './assert/proj_5/2.png'
import img3 from './assert/proj_5/3.png'
import img4 from './assert/proj_5/4.png'
import img5 from './assert/proj_5/5.png'
import img6 from './assert/proj_5/6.png'
import img7 from './assert/proj_5/7.png'
import img8 from './assert/proj_5/8.png'
import img9 from './assert/proj_5/9.png'
import img10 from './assert/proj_5/10.png'
import img11 from './assert/proj_5/11.png'
import img12 from './assert/proj_5/12.png'
import img13 from './assert/proj_5/13.png'
import img14 from './assert/proj_5/14.png'
import img15 from './assert/proj_5/15.png'
import img16 from './assert/proj_5/16.png'
import img17 from './assert/proj_5/17.png'
import img18 from './assert/proj_5/18.png'
import img19 from './assert/proj_5/19.png'
import img20 from './assert/proj_5/20.png'
import img21 from './assert/proj_5/21.png'
import img22 from './assert/proj_5/22.jpg'
import img23 from './assert/proj_5/23.jpg'
import img24 from './assert/proj_5/24.jpg'
import img25 from './assert/proj_5/25.jpg'
import img26 from './assert/proj_5/26.jpg'
import img27 from './assert/proj_5/27.jpg'


const Gzxp24005 = () => {
  const codeString = `
              
#include "arduino_secrets.h"
/* 
    Sketch generated by the Arduino IoT Cloud Thing "Untitled"
    https://create.arduino.cc/cloud/things/0545b3db-f8bb-4af1-a2b1-404dc68995ca 

    Arduino IoT Cloud Variables description

    The following variables are automatically generated and updated when changes are made to the Thing

    CloudSwitch switch1;
    CloudSwitch switch2;

    Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
    which are called when their values are changed from the Dashboard.
    These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#define sw1 13
#define sw2 12


void setup() {
    // Initialize serial and wait for port to open:
    Serial.begin(9600);
    pinMode(sw1,OUTPUT);
    pinMode(sw2,OUTPUT);
    // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
    delay(1500); 

    // Defined in thingProperties.h
    initProperties();

    // Connect to Arduino IoT Cloud
    ArduinoCloud.begin(ArduinoIoTPreferredConnection);
    
    /*
        The following function allows you to obtain more information
        related to the state of network and IoT Cloud connection and errors
        the higher number the more granular information you’ll get.
        The default is 0 (only errors).
        Maximum is 4
    */
    setDebugMessageLevel(2);
    ArduinoCloud.printDebugInfo();
}

void loop() {
    ArduinoCloud.update();
}



/*
    Since Switch1 is READ_WRITE variable, onSwitch1Change() is
    executed every time a new value is received from IoT Cloud.
*/
void onSwitch1Change()  {
    // Add your code here to act upon Switch1 change
    if(switch1){
    digitalWrite(sw1,LOW);
    Serial.println("Switch ON");
    }else{
    digitalWrite(sw1,HIGH);
    Serial.println("Switch OFF");
    }
    
}

/*
    Since Switch2 is READ_WRITE variable, onSwitch2Change() is
    executed every time a new value is received from IoT Cloud.
*/
void onSwitch2Change()  {
    // Add your code here to act upon Switch2 change
    if(switch2){
    digitalWrite(sw2,LOW);
    Serial.println("Switch ON");
    }else{
    digitalWrite(sw2,HIGH);
    Serial.println("Switch OFF");
    }
}             
            </pre>
    <h4>arduino_secrets.h</h4>
            <pre>
#define SECRET_DEVICE_KEY "rn6mZEKRqcwewefDTb19?WDgT"
#define SECRET_OPTIONAL_PASS "password"
#define SECRET_SSID "WiFi name"
            </pre>
    <h4>thingProperties.h</h4>
    <pre>
// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "4a1ba8a0-b380-4820-948c-844c2f6bd1aa";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSwitch1Change();
void onSwitch2Change();

CloudSwitch switch1;
CloudSwitch switch2;

void initProperties(){

    ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
    ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
    ArduinoCloud.addProperty(switch1, READWRITE, ON_CHANGE, onSwitch1Change);
    ArduinoCloud.addProperty(switch2, READWRITE, ON_CHANGE, onSwitch2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
    </pre>
    <h4>sketch.json</h4>
    <pre>
{
"cpu": {
    "fqbn": "esp32:esp32:esp32doit-devkit-v1",
    "name": "",
    "type": "serial"
},
"secrets": [
    {
    "name": "SECRET_DEVICE_KEY",
    "value": ""
    },
    {
    "name": "SECRET_OPTIONAL_PASS",
    "value": ""
    },
    {
    "name": "SECRET_SSID",
    "value": ""
    }
],
"included_libs": []
}`
  return (
    <>
    <div className="container">
    <div className="docs text-center p-2 my-3"><h1>VOICE COMMAND THROUGH HOME AUTOMATION SYSTEM</h1></div><hr />
    <div className="docs pb-2">
        <h2>Objective:</h2>
        <p>This project demonstrates the creation of a voice-controlled home automation system using the ESP32 microcontroller and Arduino Cloud. The ESP32 is used to communicate with the cloud platform, which allows control of home appliances using voice commands via Amazon Alexa or Google Assistant. A 2-channel relay is connected to the ESP32, acting as a switch for turning appliances on or off.</p>
    </div><hr />
    <div className="docs pb-2">
        <h2>Requirements:</h2>
            <ul>
                <li>ESP32 Microcontroller</li>
                <li>2-Channel Relay Module</li>
                <li>Arduino Cloud Account</li>
                <li>Power Supply Board</li>
                <li>Jumper Wires</li>
                <li>Amazon Alexa or Google Assistant (for voice control)</li>
                <li>PC (for Arduino Cloud setup and testing)</li>
            </ul>
    </div><hr />
    <div className="docs pb-2">
        <h2>Hardware Setup:</h2>
        <h3>Connection procedure:</h3>
        <h4>ESP32 Pin Connections:</h4>
        <p>The hardware setup consists of connecting the ESP32 board to a 2-channel relay, which is then connected to the appliances you wish to control. Here's the pin configuration:</p>
        <ul>
            <li>ESP32 Pin 13 -&gt; Relay 1 (Control for Appliance 1)</li>
            <li>ESP32 Pin 12 -&gt; Relay 2 (Control for Appliance 2)</li>
            <li>VCC -&gt; 5V Power Supply</li>
            <li>GND -&gt; Ground</li>
        </ul>
        <p>Ensure that the relay is connected properly to the respective appliances for controlling their power state.</p>
        <h3>Connection setup:</h3>
            <img 
            src={ConnectDiagram} 
            className="img-fluid rounded" 
            alt="Connection_diagram"  
            title="Connection_diagram" 
            style={{maxHeight: "400px" }}/>
    </div><hr />
    <div className="docs pb-2">
    <h2>Software Setup:</h2>
        <h3>Arduino Cloud and Voice Control Setup</h3>
            <h4>Create an Arduino Cloud Account:</h4>
                <ul>
                    <li>Go to Arduino Cloud and sign up for an account.</li>
                    <li>Click the get started button.</li>
                </ul>
                <img src={img1} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8" alt="On Started"  title="voice-control"  style={{maxWidth: "600px"}}/>

            <h4>Set up the ESP32 device in Arduino Cloud:</h4>
                <ul>
                    <li>Add a new device in Arduino Cloud by selecting the Third party device &gt; ESP32.</li>
                </ul>
                    <img src={img2} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
                    <img src={img3} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
                <ul>
                    <li>Follow the instructions to register the device. The cloud will generate a Device ID and Secret Key. </li>
                </ul>
                <img src={img4} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
                <img src={img5} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
                <img src={img6} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>

            <h4>Goto things add new things.</h4>
                <img src={img7} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
                <img src={img8} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
            <h4>Configure the setting.</h4>
                <img src={img9} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
                <img src={img10} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
            <h4>Choose Alexa for Voice Access Control.</h4>
                <img src={img11} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
            <h4>Click the Add button to add two cloud variables.</h4>
                <img src={img12} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
                <img src={img13} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
                <img src={img14} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
                <img src={img15} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
            <h4>Open sketch and paste the below code.</h4>
                <img src={img16} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>

        <h3>Code Implementation:</h3>
        <h4>Arduino code:</h4>
        <pre>{codeString}</pre>
    </div><hr />
    <div className="docs pb-2">
    <h2>Uploading the Code:</h2>
        <h3>Install the cloud Agent: </h3>
            <p>Click it: <a href="https://cloud.arduino.cc/download-agent/">Install the Arduino Cloud Agent.</a></p>
            <img src={img17} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
            <img src={img18} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
            <ul>
                <li>Open the Arduino cloud Agent.</li>
                <li>if it is open the cross mark on connection has been removed.</li>
            </ul>
            <img src={img19} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>

        
        
        <h3>Verify and upload:</h3>
        <img src={img20} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
        <img src={img21} className="img-fluid rounded col-12 col-sm-12 col-lg-8 col-xl-8 p-1" alt="Device_setup"  title="voice-control" style={{maxWidth: "600px"}}/>
    </div><hr />
    <div className="docs pb-2">
    <h2>Configure Voice Control:</h2>
        <ul>
            <li>Enable voice control by linking Arduino Cloud to Amazon Alexa or Google Assistant using the official Arduino IoT Cloud skill.</li>
            <li>Link your Alexa account to Arduino Cloud through the integration settings.</li>
        </ul>
        <div className="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-2 row-cols-xl-2">
            <div className="col text-center">
                <h4>Install the Alexa App:</h4>
                <p><b>Download the Alexa app from the App Store (iOS) or Google Play Store (Android), and sign in or create an Amazon account.</b></p>
                <img src={img22} className="img-fluid rounded col" alt="Device_setup"  title="voice-control" style={{maxWidth: "300px"}}/>
            </div>
            <div className="col text-center">
                <h4>Open Skills and Games:</h4>
                <p><b> Tap on “More” at the bottom of the app, then select “Skills & Games.”</b></p>
                <img src={img23} className="img-fluid rounded col" alt="template"  title="Automation" style={{maxWidth: "300px"}}/>
            </div>
        </div>
        <div className="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-2 row-cols-xl-2">
            <div className="col text-center">
                <h4>Search for Arduino IoT Cloud Skill: </h4>
                <p><b>In the search bar, type “Arduino IoT Cloud” and find the official Arduino skill. Tap on it.</b></p>
                <img src={img24} className="img-fluid rounded col" alt="template"  title="Automation" style={{maxWidth: "300px"}}/>
            </div>
            <div className="col text-center">
                <h4>Enable the Skill: </h4>
                <p><b> Tap “Enable to Use.” </b></p>
                <img src={img25} className="img-fluid rounded col" alt="template"  title="Automation" style={{maxWidth: "300px"}}/>
            </div>

        </div>
        
            

        <ul>
            <li>You’ll be prompted to sign in with your Arduino account credentials. </li>
            <li>Be sure this is the same account you use for your Arduino Cloud.</li>
        </ul>
            <div className="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-2 row-cols-xl-2">
                <div className="col text-center p-2">                    
                    <img src={img26} className="img-fluid rounded col text-center" alt="template"  title="Automation" style={{maxWidth: "300px"}}/>
                </div>
                <div className="col text-center p-2">
                    <img src={img27} className="img-fluid rounded col" alt="template"  title="Automation" style={{maxWidth: "300px"}}/>
                </div>
            </div>
            <div>
                <h4>Allow Device Discovery:</h4>
                <p>Once connected, Alexa will automatically search for devices associated with your Arduino IoT Cloud account. The devices should appear in your Alexa app.</p>
                <h4>Rename Devices (Optional):</h4>
                <p>You can rename devices for easier identification, like "Room Light" or "Fan."</p>
                <h4>Use Voice Commands: </h4>
                <p> Now, you can control your Arduino IoT Cloud-connected devices with commands like:</p>
                <ul>
                    <li>“Alexa, turn on the room light.”</li>
                    <li>“Alexa, turn off the fan.”</li>
                </ul>
            </div>
    </div><hr />
    <div className="docs pb-2">
    <h2>Testing and operation:</h2>
        <h4>Upload the Code:</h4>
            <ul>
                <li>After configuring the cloud and coding, upload the code to your ESP32 board using the Arduino IDE.</li>
            </ul>
        <h4>Connect to WiFi:</h4>
            <ul>
                <li>Ensure the ESP32 is connected to the WiFi network specified in the code.</li>
            </ul>
        <h4>Voice Command Testing:</h4>
            <ul>
                <li>Once the ESP32 is connected to the cloud, use Amazon Alexa or Google Assistant to control the appliances using voice commands like:
                    <ul>
                        <li>Turn on the room light.</li>
                        <li>Turn off the fan.</li>
                    </ul>
                </li>
            </ul>
        <h4>Monitoring through Arduino Cloud:</h4>
            <ul>
                <li>You can also monitor and control the appliances from the Arduino Cloud dashboard.</li>
            </ul>
    </div><hr />
    <div className="docs pb-2">
        <h2>Conclusion:</h2>  
        <p>This project demonstrates a simple, yet effective, method for controlling home appliances using voice commands via ESP32 and Arduino Cloud. The system is easy to set up and provides a modern, user-friendly solution for home automation. By using cloud integration and IoT platforms, users can control appliances remotely and with voice commands, making it a practical solution for smart homes.	</p>
    </div>
</div><hr />
</>
  )
}

export default Gzxp24005